# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Sub-WrapPackages
version:      1.2
version_from: 
installdirs:  site
requires:
    Hook::LexWrap:                 0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
